import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import RecoilContextProvider from "@/lib/_app";
import Copyright_Link from "@/components/Copyright_Link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
      <RecoilContextProvider>
         {children}
      </RecoilContextProvider> 
      <Copyright_Link/>
      </body>
    </html>
  );
}
